name: "chicago_311"
version: "1.0.0"
config-version: 2

profile: "chicago_311"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  chicago_311:
    staging:
      +materialized: view

    marts:
      +materialized: table