version: 2

models:
  - name: fct_service_requests
    columns:
      - name: sr_number
        data_tests:
          - not_null
          - unique

      - name: ward_version_key
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_ward')
                field: ward_version_key
      - name: community_area
        data_tests:
          - not_null:
              config:
                severity: warn